language: python
matrix:
  include:
    - name: "Python 3.5"
      dist: xenial
      python: 3.5
    - name: "Python 3.6"
      dist: bionic
      python: 3.6
    - name: "Python 3.7"
      dist: cosmic
      python: 3.7
install:
  - pip install .
script:
  - pytest
