language: python
matrix:
  include:
    - name: "Python 3.5"
      dist: xenial
      python: 3.5
    - name: "Python 3.6"
      dist: bionic
      python: 3.6
    - name: "Python 3.7"
      dist: cosmic
      python: 3.7
    - name: "Docs"
      dist: cosmic
      python: 3.7
      # Because we are using multiple extra packages, installation is much more
      # involved and we use conda.
      install:
        - pip install --user -r requirements.txt
        - pip install .
      script:
        - make -C doc html
        - make -C doc latex
install:
  - pip install .
script:
  - pytest
