language: python
matrix:
  include:
    - name: "Python 3.5"
      dist: xenial
      python: 3.5
    - name: "Python 3.6"
      dist: bionic
      python: 3.6
    - name: "Python 3.7"
      dist: cosmic
      python: 3.7
    - name: "Docs"
      dist: cosmic
      python: 3.7
      # Because we are using multiple extra packages, installation is much more
      # involved and we use conda.
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - source "$HOME"/miniconda/etc/profile.d/conda.sh
        - conda config --set always_yes yes --set changeps1 no
        - conda env create -f environment.yml
        - conda activate jupyter-sphinx
        - python -m ipykernel install --user --name python3 --display-name "Python3"
        - pip install .
      script:
        - make -C doc html
        - make -C doc latex
install:
  - pip install .
script:
  - pytest
