version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      # Install
      - run:
          name: Installation and docs build
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            source "$HOME"/miniconda/etc/profile.d/conda.sh
            conda config --set always_yes yes --set changeps1 no
            conda env create -f environment.yml
            conda activate jupyter-sphinx
            python -m ipykernel install --user --name python3 --display-name "Python3"
            pip install --user .

            cd doc
            make html




      - store_artifacts:
          path: doc/build/html/
          destination: html


workflows:
  version: 2
  build_docs:
    jobs:
      - build_docs
