version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      # Install
      - run:
          name: Install dependencies
          command: |
            pip install --user -r requirements.txt
            pip install --user .
      - run:
          name: Build documentation
          command: |
            cd doc
            make html-strict

      - store_artifacts:
          path: doc/build/
          destination: build


workflows:
  version: 2
  build_docs:
    jobs:
      - build_docs
